# Generated by Django 4.0.6 on 2022-08-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='sex',
            new_name='gender',
        ),
    ]
