# Generated by Django 4.0.6 on 2022-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orderitem_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='process',
            field=models.BooleanField(default=True),
        ),
    ]
