# Generated by Django 4.0.6 on 2022-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='process',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
