# Generated by Django 4.0.6 on 2022-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='process',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
