# Generated by Django 4.0.6 on 2022-09-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='process',
            field=models.BooleanField(default=True),
        ),
    ]
