# Generated by Django 4.0.6 on 2022-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20)),
                ('product_slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('product_price', models.PositiveIntegerField(blank=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_count', models.PositiveIntegerField(blank=True)),
                ('product_available', models.BooleanField(blank=True)),
                ('product_img', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product_base',
                'ordering': ('product_slug',),
            },
        ),
    ]
