# Generated by Django 4.0.6 on 2022-08-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=30)),
                ('slug_category', models.SlugField(max_length=30, unique=True)),
                ('description_category', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'products_categorymodel',
                'ordering': ('slug_category',),
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20)),
                ('product_slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('product_price', models.PositiveIntegerField(blank=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_count', models.PositiveIntegerField(blank=True)),
                ('product_available', models.BooleanField(blank=True)),
                ('product_img', models.URLField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categorymodel')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product_base',
                'ordering': ('product_slug',),
            },
        ),
    ]
