# Generated by Django 4.0.6 on 2022-08-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'products_categorymodel',
                'ordering': ('slug',),
            },
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('slug',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_slug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categorymodel'),
        ),
    ]
