# Generated by Django 4.0.6 on 2022-08-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorymodel_productmodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ('slug_category',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='products_categorymodel',
        ),
    ]
