# Generated by Django 4.0.6 on 2022-09-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
